name: ascent-stg
services:

  ascent:
    build:
      context: .
      dockerfile: Dockerfile
    image: ascent-stg:0.0.7
    pull_policy: build
    container_name: ascent-stg
    restart: unless-stopped
    environment:
      SPRING_PROFILES_ACTIVE: stg
      AE_MYSQL_USER: ${AE_MYSQL_USER:-ascent-stg}
      AE_MYSQL_PASSWORD: ${AE_MYSQL_PASSWORD:-ascent-stg}
      AE_MYSQL_DATABASE: ${AE_MYSQL_DATABASE:-ascent-stg}
      AE_REDIS_PASSWORD: ${AE_REDIS_PASSWORD:-ascent-stg}
    ports:
      - "${AE_ASCENT_HOST_PORT:-8082}:8080"
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.4.2
    container_name: mysql-stg
    restart: unless-stopped
    environment:
      MYSQL_USER: ${AE_MYSQL_USER:-ascent-stg}
      MYSQL_PASSWORD: ${AE_MYSQL_PASSWORD:-ascent-stg}
      MYSQL_DATABASE: ${AE_MYSQL_DATABASE:-ascent-stg}
      MYSQL_ROOT_PASSWORD: ${AE_MYSQL_ROOT_PASSWORD:-ascent-stg}
    ports:
      - "${AE_MYSQL_HOST_PORT:-3307}:3306"
    volumes:
      - ./volumes/ascent-stg/mysql-stg:/var/lib/mysql

  redis:
    image: redis:7.4.0
    container_name: redis-stg
    restart: unless-stopped
    command: redis-server --requirepass ${AE_REDIS_PASSWORD:-ascent-stg}
    ports:
      - "${AE_REDIS_HOST_PORT:-6380}:6379"
    volumes:
      - ./volumes/ascent-stg/redis-stg:/data