spring:
  datasource:
    url: jdbc:mysql://mysql:3306/${AE_MYSQL_DATABASE}
    username: ${AE_MYSQL_USER}
    password: ${AE_MYSQL_PASSWORD}
  data:
    redis:
      host: redis
      port: 6379
      password: ${AE_REDIS_PASSWORD}