server:
  port: 8080
  servlet:
    session:
      cookie:
        name: AC-SESSION
logging:
  level:
    root: info
  pattern:
    correlation: '[%X{AL-CORRELATION}] '
spring:
  profiles:
    default: dev
    active: '@spring.profiles.active@'
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  session:
    store-type: redis
    redis:
      namespace: ascent
  cache:
    type: redis
    redis:
      key-prefix: ascent:cache
      time-to-live: 3600000